version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: graphql
    versions:
    - 1.12.7
  - dependency-name: rspec-support
    versions:
    - 3.10.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/ci/ruby2.6"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 2.7"
- package-ecosystem: docker
  directory: "/ci/ruby2.5"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 2.6"
- package-ecosystem: docker
  directory: "/ci/ruby2.4"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 2.5"
- package-ecosystem: docker
  directory: "/ci/ruby2.7"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 3.0"
- package-ecosystem: docker
  directory: "/ci/ruby3.0"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
