rspec_task:
  container:
    matrix:
      dockerfile: ci/ruby2.3/Dockerfile
      dockerfile: ci/ruby2.4/Dockerfile
      dockerfile: ci/ruby2.5/Dockerfile
      dockerfile: ci/ruby2.6/Dockerfile
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: echo $RUBY_VERSION && cat Gemfile.lock
    populate_script: bundle install
  rspec_script: rspec
